version: 2
checks:
  method-lines:
    enabled: false
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        # Standard configuration.
        - TODO
        - FIXME
        - HACK
        - XXX
        - BUG
        # Doxygen variants.
        - '@todo'
        - '@fixme'
  phpcodesniffer:
    enabled: true
    config:
      standard: Drupal,DrupalPractice
  scss-lint:
    enabled: true
exclude_patterns:
  - authorize.php
  - cron.php
  - includes/
  - index.php
  - install.php
  - misc/
  - modules/
  - private/
  - profiles/
  - scripts/
  - sites/*.php
  - sites/all/modules/contrib/
  - sites/all/drush/
  - sites/all/libraries/
  - sites/default/
  - tests/
  - themes/
  - update.php
  - xmlrpc.php
  - "**/node_modules/"
  - "**/contrib/"
  - "**/vendor/"
  - "**/gulpfile.js"
  # Ignore generated CSS
  - sites/all/themes/orwell/css/
  - sites/all/themes/pratchett/css/
  # Generated Features code
  - '**/*.features.*'
  - '**/*.feeds_importer_default.inc'
  - '**/*.field_group.inc'
  - '**/*.file_default_displays.inc'
  - '**/*.layouts.inc'
  - '**/*.pages_default.inc'
  - '**/*.panels_default.inc'
  - '**/*.panelizer.inc'
  - '**/*.strongarm.inc'
  - '**/*.views_default.inc'
