assets:
  - database.sql.gz
steps:
  - name: Build site
    plugin: Drupal
    database: database.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: true
  # - name: Enable stage_file_proxy
  #   command: 'drush --root="/var/www/html" en stage_file_proxy -y && drush variable-set stage_file_proxy_origin "http://ereolen.dk"'
