version: '2'
services:
  ereol:
    build: './private/docker/web'
    ports:
      - 80
    links:
      - db-ereol
    volumes:
      - './:/var/www/html'
      - './private/docker/sites/ereol:/var/www/html/sites/default'
    environment:
      MYSQL_HOST: db-ereol
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  ego:
    build: './private/docker/web'
    ports:
      - 80
    links:
      - db-ereol
    volumes:
      - './:/var/www/html'
      - './private/docker/sites/ego:/var/www/html/sites/default'
    environment:
      MYSQL_HOST: db-ego
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  db-ereol:
    image: mariadb:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - './private/docker/db-init/ereol:/docker-entrypoint-initdb.d'

  db-ego:
    image: mariadb:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - './private/docker/db-init/ego:/docker-entrypoint-initdb.d'

  # eReolen Go theme
  gulp:
    image: reload/gulp:3.9.1
    volumes:
      - './sites/all/themes/wille:/src'

  # eReolen theme
  compass:
    build: './private/docker/gulp-compass'
    volumes:
      - './sites/all/themes/brin:/src'
